name: CI Pipeline

on:
  push:
    branches:
      - main  # Ejecuta el workflow al hacer push a la rama principal
  pull_request:
    branches:
      - main  # Ejecuta el workflow al abrir un PR hacia la rama principal

jobs:
  cypress-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]  # Define sistemas operativos
        node-version: [14, 16, 18]  # Define versiones de Node.js
    
    steps:
      - name: Check out code
        uses: actions/checkout@v2  # Clona el repositorio
        
      - name: Set up Node.js
        uses: actions/setup-node@v3  # Configura Node.js en la versión especificada
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install  # Instala las dependencias del proyecto
      
      - name: Install Cypress
        run: npm install cypress --save-dev  # Instala Cypress como dependencia de desarrollo

      - name: Run Cypress tests
        run: npx cypress run  # Ejecuta las pruebas de Cypress
